ALL_PLAYERS_FIELDNAMES = ['number of player', 'Name', 'Birthday', 'Chess national ID', 'Score']
TOURNAMENT_FIELDNAMES = ['Tournament name']
DATE_AND_PLACE_TOURNAMENT = ['Date', 'Place']
PLAYERS_TOURNAMENT_FIELDNAMES = ['Name of player']
ROUND_AND_MATCHES_FIELDNAMES = ['Round', 'Matches']
